### ISSUE TITLE
Showing error while importing the file to blender

### ISSUE THREAD

**Issue by Rejin-dev** [adroitwhiz/after-effects-to-blender-export#19]
Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 606, in execute
    self.import_property_spatial(
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 355, in import_property_spatial
    self.import_property(
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 252, in import_property
    prop_data['supersampling'],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'supersampling'

**Comment by adroitwhiz** [comment]
Can you share the .json file that isn't getting imported properly?

**Comment by adroitwhiz** [comment]
Try the latest version of the Blender addon (0.5.3) and let me know if it fixes the issue.
