### ISSUE TITLE
after effect to blender addon error in blender 4.1

### ISSUE THREAD

**Issue by mashood321** [adroitwhiz/after-effects-to-blender-export#20]
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 606, in execute
    self.import_property_spatial(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 355, in import_property_spatial
    self.import_property(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 252, in import_property
    prop_data['supersampling'],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'supersampling'
**Describe the bug**
<!-- A clear description of what the bug is. -->

**Error message**
<!-- What error message is Blender giving you?
     You can find this by clicking "Toggle System Console" in the Window menu at the top. -->

**To Reproduce**
<!--
Steps to reproduce the behavior; e.g.
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
-->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Test Case**
<!-- If possible, include the .json file that causes the issue. -->

**Platform Info**
- <!-- Operating system + version -->
- <!-- Blender version -->

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by adroitwhiz** [comment]
Hi,

I see you haven't read the bug report template or filled it out. Please upload the .json file that's giving you the error and take a screenshot of the settings you used when exporting and importing.

**Comment by Shevy-D** [comment]
Hello, I have almost the same issue:
Python: Traceback (most recent call last):
  File "C:\Users\dmitr\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import-comp-to-blender.py", line 408, in execute
    if layer['nullLayer']:
       ~~~~~^^^^^^^^^^^^^
KeyError: 'nullLayer'


Can you help me? I uploaded the .json file that's giving me the error and a screenshot of the settings I used when exporting and importing.
[Track.json](https://github.com/user-attachments/files/15520158/Track.json)
![image](https://github.com/adroitwhiz/after-effects-to-blender-export/assets/96663113/3f077b66-14d4-4234-9f82-ffb4a92f3030)
![image](https://github.com/adroitwhiz/after-effects-to-blender-export/assets/96663113/4f8fdd4d-9b48-4908-b71a-e3a38ca5907c)
![image](https://github.com/adroitwhiz/after-effects-to-blender-export/assets/96663113/eb5d498b-613b-42ba-8aae-5d3e2ad0dec4)

**Comment by adroitwhiz** [comment]
Try the latest version of the Blender addon (0.5.3) and let me know if it fixes the issue.

**Comment by adroitwhiz** [comment]
Closing this issue as there's been no response for a year.
