### ISSUE TITLE
Error when importing json file into Blender

### ISSUE THREAD

**Issue by PierreDidier** [adroitwhiz/after-effects-to-blender-export#6]
Hello, I'm trying to import my json file into Blender but I have an error in the console. I use blender 2.9.0 and the last version of After Effects

**Error message**

"Traceback (most recent call last):
  File "C:\Users\Pierre\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\import-comp-to-blender.py", line 493, in execute
    add=-data['comp']['width'] * 0.5 * self.scale_factor if should_translate else 0
  File "C:\Users\Pierre\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\import-comp-to-blender.py", line 183, in import_property
    add
  File "C:\Users\Pierre\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\import-comp-to-blender.py", line 139, in import_baked_keyframe_channel
    k.co_ui = [i + start_frame, keyframe * mul + add]
AttributeError: 'Keyframe' object has no attribute 'co_ui'

location: <unknown location>:-1"

**Screenshots**

<img width="673" alt="Blender" src="https://user-images.githubusercontent.com/74496843/157083258-a01e4561-1cf7-493b-8787-c5333d2c3d5e.png">

**Comment by adroitwhiz** [comment]
Try upgrading your Blender version.
